version: "3.8"

volumes:
  db_volume:

# If you need to keep the container running,
# command: tail -f /dev/null
services:
  # Web Application Server (Django)
  backend:
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    restart: always
    command: >
      sh -c "
      python manage.py makemigrations admin_honeypot django_q
      && python manage.py migrate
      && python manage.py collectstatic --noinput --verbosity 0
      && gunicorn config.wsgi:application"
    env_file: .env.dev

  # Web Server (Nginx)
  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./backend/static/media/:/media/
      - ./backend/static/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
