version: "3.8"

volumes:
  db_volume:

services:
  # If you need to keep the container running,
  # command: tail -f /dev/null

  # Database Server (Postgres)
  database:
    image: postgres:latest
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file: .env.dev

  # Web Application Server (Django)
  backend:
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    env_file: .env.dev
    command: >
      sh -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput --verbosity 0
      && gunicorn"
    volumes:
      - ./backend:/app
    restart: always

  # Web Server (Nginx)
  web:
    depends_on:
      - backend
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./backend/static/media/:/media/
      - ./backend/static/static/:/static/
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf:ro
