FROM python:3.9

# python environment value setting
ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

# python dependency library install
COPY ./requirements/common.txt ./requirements/prod.txt /app/requirements/
RUN pip install -r /app/requirements/prod.txt

# copy project files
COPY . /app

# change work directory
WORKDIR /app
