version: "3.8"

volumes:
  db_volume:

# If you need to keep the container running,
# command: tail -f /dev/null
services:
  # Database Server (Postgres)
  database:
    image: postgres:latest
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  # Web Application Server (Django)
  backend:
    depends_on:
      - database
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.dev
    env_file: ../backend/env/dev.env
    command: >
      sh -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput --verbosity 0
      && gunicorn -c ./gunicorn.conf.py config.wsgi:application"
    volumes:
      - ../backend:/app
    restart: always

  # Web Server (Nginx)
  web:
    depends_on:
      - backend
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ../backend/static/media/:/media/
      - ../backend/static/static/:/static/
      - ../nginx/dev.conf:/etc/nginx/nginx.conf:ro
