version: "3.8"

services:
  # If you need to keep the container running,
  # command: tail -f /dev/null

  # Database Server (Postgres)
  database:
    image: postgres:latest
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file: .env.prod
    restart: always

  # Application Server (Django)
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
    env_file: .env.prod
    command: >
      sh -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput --verbosity 0
      && gunicorn"
    restart: always

  # Web Server (Nginx)
  web:
    build:
      context: ./nginx/sa
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    env_file: .env.prod
    command: >
      sh -c "
      envsubst '$$NGINX_STATIC_STORAGE_BUCKET_URL $$NGINX_MEDIA_STORAGE_BUCKET_URL' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

volumes:
  db_volume:
