# Generated by Django 3.2 on 2021-06-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nestedresource',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='example.collection'),
        ),
    ]
