# Generated by Django 3.2 on 2021-06-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_nestedresource_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='nestedcollection',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='nestedresource',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='nestedcollection',
            unique_together={('parent', 'title')},
        ),
    ]
